nome: Windows Cloud PC - Anydesk (Otimizado)

sobre:
  fluxo de trabalho_despacho:

empregos:
  construir:
    nome: Comece a construir...
    em execução: windows-latest
    timeout-minutos: 10080 # Máximo de 7 dias para evitar tempo de execução excessivo

    passos:
      - nome: Baixando e instalando o Essentials
        executar: |
          # Baixe o arquivo .bat para instalar componentes essenciais
          Invocar-WebRequest -Uri "https://www.dropbox.com/scl/fi/7eiczvgil84czu55dxep3/Downloads.bat?rlkey=wzdc1wxjsph2b7r0atplmdz3p&dl=1" -OutFile "Downloads.bat"
          # Executa o script .bat para instalar os componentes
          cmd /c Downloads.bat

      - nome: Faça login no AnyDesk
        executar: |
          # Verifique se o arquivo start.bat existe antes de executar
          se (Caminho-de-Teste "start.bat") {
            cmd /c start.bat
          } outro {
            Write-Host "Arquivo start.bat não encontrado. Verifique a configuração."
          }

      - nome: Monitore e reinicie o AnyDesk se necessário
        executar: |
          # Monitore a conexão do AnyDesk e reinicie se necessário
          enquanto ($true) {
            $process = Get-Process -Name "AnyDesk" -ErrorAction Continuar Silenciosamente
            se (-não $processo) {
              Write-Host "AnyDesk não está rodando, reiniciando..."
              cmd /c start.bat
            }
            Start-Sleep -Seconds 300 # Verifique a cada 5 minutos
          }

      - nome: Contador de tempo (tarefa de longa duração)
        executar: |
          #Configura para manter a máquina em execução
          Start-Sleep -Seconds 604800 # 7 dias de execução contínua

      - nome: Limpar arquivos temporários
        if: sucesso() # Executa esta etapa apenas se todas as etapas anteriores foram bem-sucedidas
        executar: |
          # Remove arquivos temporários ou logs gerados
          Remover-Item Downloads.bat -Forçar
          Write-Host "Limpeza completa."
